### ISSUE TITLE
Does DialogueTester work with Heart Events?

### ISSUE THREAD

**Issue by ctb116** [DecidedlyHuman/StardewValleyMods#7]
Hey, we are using DialogueTester - it's a wonderful mod! We were wondering if it works with Heart Events. For example, Shane's six heart event is found in Data\Events\Forest.json and the ID for it is `3910975/f Shane 1500/e 3910674/t 900 2000/w rainy`

We've tried:

dh_testdialogue 3910975/f Shane 1500/e 3910674/t 900 2000/w rainy Shane
dh_testdialogue Data\Events\Forest:3910975/f Shane 1500/e 3910674/t 900 2000/w rainy Shane -manual

We get an error that there are too many arguments. It doesn't seem like this mod can test heart events but we wanted to check just in case.

**Comment by atravita-mods** [comment]
Dialogue Tester probably does not work for events, but you can launch an event with `debug ebi eventID` (ie `debug ebi 3910975`) as long as you are NOT standing on the map the event activates on.

**Comment by ctb116** [comment]
Thank you both! That is really helpful.
